# Generated by Django 5.2.16 on 2026-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('driver', models.CharField(choices=[('agilent_34401a', 'Agilent 34401A'), ('keysight_34461a', 'Keysight 34461A')], max_length=32)),
                ('address', models.CharField(help_text='Device path such as /dev/ttyUSB0 or /dev/usbtmc0.', max_length=255)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('error', 'Error')], default='offline', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('manufacturer', 'model_name', 'name'),
            },
        ),
    ]
