# Generated by Django 5.2.16 on 2026-07-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='last_driver_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_driver_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_identification',
            field=models.TextField(blank=True),
        ),
    ]
