# Generated by Django 5.2.16 on 2026-07-26 16:45

from django.db import migrations, models


def rename_online_status(apps, schema_editor):
    """Rename the former successful-test status to reachable."""
    instrument = apps.get_model("main", "Instrument")
    instrument.objects.filter(status="online").update(status="reachable")


def restore_online_status(apps, schema_editor):
    """Restore the former status value when reversing the migration."""
    instrument = apps.get_model("main", "Instrument")
    instrument.objects.filter(status="reachable").update(status="online")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_measurement'),
    ]

    operations = [
        migrations.RunPython(rename_online_status, restore_online_status),
        migrations.AlterField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('reachable', 'Reachable'), ('error', 'Error')], default='offline', max_length=16),
        ),
    ]
