# Generated by Django 5.2.16 on 2026-07-27 16:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_instrument_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('dc_voltage', 'DC voltage')], max_length=50)),
                ('mode', models.CharField(choices=[('single', 'Single'), ('continuous', 'Continuous'), ('loop', 'Loop')], max_length=16)),
                ('interval', models.FloatField(blank=True, help_text='Seconds between readings.', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('requested_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_runs', to='main.instrument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='main.measurementrun'),
        ),
    ]
