# Generated by Django 5.2.16 on 2026-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_measurement_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='address',
            field=models.CharField(help_text='Device path such as /dev/ttyUSB0 or /dev/usbtmc0, or mock://default.', max_length=255),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='driver',
            field=models.CharField(choices=[('agilent_34401a', 'Agilent 34401A'), ('keysight_34461a', 'Keysight 34461A'), ('mock', 'Mock instrument')], max_length=32),
        ),
    ]
