# Generated by Django 5.2.16 on 2026-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_mock_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementrun',
            name='function',
            field=models.CharField(choices=[('dc_voltage', 'DC voltage'), ('ac_voltage', 'AC voltage'), ('resistance', 'Resistance')], max_length=50),
        ),
    ]
