# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_add_ac_voltage_and_resistance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementrun",
            name="function",
            field=models.CharField(
                choices=[
                    ("dc_voltage", "DC voltage"),
                    ("ac_voltage", "AC voltage"),
                    ("dc_current", "DC current"),
                    ("ac_current", "AC current"),
                    ("resistance", "Resistance"),
                    ("temperature", "Temperature"),
                ],
                max_length=50,
            ),
        ),
    ]
