# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_add_mock_dc_power_supply"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="show_sidebar",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="show_top_navigation",
            field=models.BooleanField(default=True),
        ),
    ]
