# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_userpreference_navigation_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="sidebar_position",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")],
                default="left",
                max_length=8,
            ),
        ),
    ]
