# Generated by Django 5.2.16 on 2026-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_mock_dmm_address_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='driver',
            field=models.CharField(choices=[('agilent_34401a', 'Agilent 34401A'), ('keysight_34461a', 'Keysight 34461A'), ('mock-dmm', 'Mock DMM'), ('mock_dc_power_supply', 'Mock DC Power Supply'), ('rnd_ka3005p', 'RND Lab 320-KA3005P')], max_length=32),
        ),
    ]
