# Generated by Django 5.2.16 on 2026-07-28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0010_add_mock_dc_power_supply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("voltage_mode", models.CharField(choices=[("fixed", "Fixed"), ("sweep", "Sweep"), ("cycle", "Cycle")], default="sweep", max_length=16)),
                ("voltage_source", models.CharField(choices=[("external", "External"), ("virtual", "Virtual power supply")], default="virtual", max_length=16)),
                ("start_voltage", models.DecimalField(decimal_places=3, max_digits=6)),
                ("stop_voltage", models.DecimalField(decimal_places=3, max_digits=6)),
                ("voltage_step", models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0.001)])),
                ("interval_seconds", models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ("cycle_count", models.PositiveIntegerField(default=1)),
                ("temperature_min", models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ("temperature_max", models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ("temperature_resolution", models.DecimalField(decimal_places=2, default=0.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("temperature_seed", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("completed", "Completed"), ("stopped", "Stopped"), ("failed", "Failed")], default="pending", max_length=16)),
                ("stop_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("power_supply", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="power_supply_tasks", to="main.instrument")),
                ("temperature_meter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="temperature_measurement_tasks", to="main.instrument")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="automation_tasks", to=settings.AUTH_USER_MODEL)),
                ("voltage_meter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="voltage_measurement_tasks", to="main.instrument")),
            ],
            options={"ordering": ("-created_at", "-pk")},
        ),
        migrations.CreateModel(
            name="TaskSample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.PositiveIntegerField()),
                ("voltage_setpoint", models.DecimalField(decimal_places=3, max_digits=6)),
                ("measured_voltage", models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ("temperature", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="samples", to="tasks.automationtask")),
            ],
            options={"ordering": ("index",)},
        ),
        migrations.AddConstraint(
            model_name="tasksample",
            constraint=models.UniqueConstraint(fields=("task", "index"), name="tasks_unique_sample_index"),
        ),
    ]
