# Generated by Django 5.2.16 on 2026-07-28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_add_mock_dc_power_supply"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationtask",
            name="power_supply",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="power_supply_tasks", to="main.instrument"),
        ),
        migrations.AlterField(
            model_name="automationtask",
            name="start_voltage",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="automationtask",
            name="stop_voltage",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="automationtask",
            name="voltage_step",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name="automationtask",
            name="interval_seconds",
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name="automationtask",
            name="requested_samples",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="TaskInstrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("configuration", models.JSONField(default=dict)),
                ("instrument", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="automation_task_assignments", to="main.instrument")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_instruments", to="tasks.automationtask")),
            ],
            options={"ordering": ("order", "pk")},
        ),
        migrations.AddConstraint(
            model_name="taskinstrument",
            constraint=models.UniqueConstraint(fields=("task", "instrument"), name="tasks_unique_instrument_per_task"),
        ),
        migrations.CreateModel(
            name="TaskReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parameter", models.CharField(max_length=50)),
                ("value", models.DecimalField(decimal_places=6, max_digits=16)),
                ("unit", models.CharField(max_length=20)),
                ("sample", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="readings", to="tasks.tasksample")),
                ("task_instrument", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="readings", to="tasks.taskinstrument")),
            ],
            options={"ordering": ("task_instrument__order", "pk")},
        ),
    ]
