# Generated by Django 5.2.16 on 2026-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_flexible_task_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
