# Generated by Django 5.2.16 on 2026-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_automationtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='measurement_mode',
            field=models.CharField(choices=[('single', 'Single'), ('continuous', 'Continuous'), ('loop', 'Loop')], default='single', max_length=16),
        ),
    ]
