# Generated by Django 5.2.16 on 2026-07-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_automationtask_measurement_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreading',
            name='task_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='tasks.taskinstrument'),
        ),
    ]
