# Generated by Django 5.2.16 on 2026-07-31 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskreading_task_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='interval_seconds',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
