# Generated by Django 5.2.16 on 2026-07-31 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_automationtask_interval_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksample',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
