# Generated by Django 5.2.16 on 2026-07-31 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasksample_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='start_delay_seconds',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
